### ISSUE TITLE
Create an option to set the number of threads

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/pytest-freethreaded#1]
Create a pytest option to set the number of threads to spawn for the threadpool

See 
https://github.com/pytest-dev/pytest-repeat/blob/main/pytest_repeat.py#L10-L24 for an example.

The configuration option should be called `threads`

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme

you may need to install the c compiler

**Comment by glandium** [comment]
I think we need to use one of the runtest hooks: https://docs.pytest.org/en/stable/reference/reference.html#test-running-runtest-hooks

**Comment by glandium** [comment]
Relevant documentation from pytest-xdist: https://github.com/pytest-dev/pytest-xdist/blob/cbbb894e71071dce40f59ca429f9ea780c39aa64/docs/how-it-works.rst

**Comment by glandium** [comment]
Fixed in 24b1025b966b614ddd9022b4f55f60b2ee98dbb7
