### ISSUE TITLE
During pytest initialization, fail if the GIL is enabled

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/pytest-freethreaded#2]
Tasks: 

1. Research how to determine if the GIL is enabled at runtime (see `sys` module documentation for 3.13)
2. Add an assertion in `pytest_sessionstart` hook https://github.com/tonybaloney/pytest-freethreaded/blob/main/pytest_freethreaded.py#L5

**Comment by SagarChandra07** [comment]
maybe this will help

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme

you may need to install the c compiler

**Comment by NCLI** [comment]
lol
